---
- name: Install NGINX
  apt:
    name: nginx
    state: present
  become: yes

- name: Copy NGINX config
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/conf.d/yii2.conf
  notify: Restart nginx
  become: yes

