version: '3.8'

services:
  yii2-app:
    image: admin807/yii2app:latest
    build: .
    ports:
      - "9000:9000"
    networks:
      - webnet
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

networks:
  webnet:
    driver: overlay
