- name: Clone Yii2 repo
  git:
    repo: https://github.com/1235keerti/yii2-app.git
    dest: /home/ubuntu/yii2-app
    version: main
    force: yes
  become: yes

- name: Deploy or Update Yii2 Docker Swarm service
  shell: |
    docker service ls | grep -q yii2app_yii2-app && \
    docker service update --image {{ image_tag }} yii2app_yii2-app || \
    docker service create \
      --name yii2app_yii2-app \
      --publish 9000:80 \
      --replicas 1 \
      {{ image_tag }}
  become: yes

