name: CI/CD Deploy to Docker Swarm

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: admin807/yii2app

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Docker Image Tag
        run: echo "IMAGE_TAG=${IMAGE_NAME}:${{ github.sha }}" >> $GITHUB_ENV

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker Image
        run: docker build -t $IMAGE_TAG .

      - name: Push Docker Image
        run: docker push $IMAGE_TAG

      - name: SSH and Deploy to EC2 (Docker Swarm)
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            sudo apt update
            sudo apt install -y ansible
            ansible-playbook -i localhost, playbook.yml --connection=local --extra-vars "image_tag=admin807/yii2app:${{ github.sha }}"

            
            

